name: Build and Publish Docker Image
on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  build_and_publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Lowercase Repo
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - name: use REPO
        run: echo "The value of REPO is: ${REPO}"    
      - name: Checkout 
        uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Container
        if: ${{ github.event_name != 'release' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ghcr.io/${REPO}:latest
      - name: Build and Push Docker Container
        if: ${{ github.event_name == 'release' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ghcr.io/${REPO}:latest,
            ghcr.io/${REPO}:${{ github.ref_name }},
            
